export const imageUrl = "http://195.35.45.56:8002/uploads/"
export const MainUrl = "http://195.35.45.56:8002/"
export const endPoint = {
    categoryGet:"book/get-category",
    getBookList:"book/get-books",
    getAllEbooks:"book/getAllEBooks",
    getBooksByCategory:"book/get-books-by-category-id",
    getPoster:"book/get-poster",
    login:"auth/login",
    signup:"auth/signup",
    addFeedback:"book/add-feedback",
    addToCart:"book/add-book-to-cart",
    addToCartByUserId:"book/add-book-to-cart-by-userid",
    getBooksFromCart:"book/get-book-from-cart-by-ip",
    getBookFromCartByUserId:"book/get-book-from-cart-by-userid",
    addSupport:"support/add-support-request",
    removeItem:"book/remove-item-from-cart",
    promotionAndOffer:"book/get-permotion-&-offer",
    socialMediaUrl:"socialmedia/get-social-media-url",
    trendingTitleAndImages:"book/get-trending-title-&-images",
    adminInformation:"book/get-admin-info",
    bookDetailsById:"book/get-bookdetail-by-id",
    getcarttotalamountandquentity:"book/get-cart-info",
    getcarttotalamountandquentityyuserid:"book/get-cart-info-by-userid",
    getCurrentAffairs:"currentAffairs/getCurrentAffairsFiles",
    getTestSeries:"testSeries/getTestSeries",
    addTypingForm:"typing/addTypingForm",
    getAllDesign:"design/getAllDesign",
    addDataTranslate:"datatranslate/addDataTranslateFormDetails",
    getallPreviousYearPaper:"paper/getallPreviousYearPaper",
}